SELECT GETDATE()
SELECT SYSDATETIME()
SELECT SYSDATETIMEOFFSET()


SELECT DATEADD(DAY, 10, SYSDATETIME())
SELECT DATEADD(MONTH, 10, SYSDATETIME())
SELECT DATEADD(YEAR, 10, GETDATE())


SELECT DATEDIFF(DAY, '1992.12.08', SYSDATETIME())
SELECT DATEDIFF(MONTH, '1992.12.08', SYSDATETIME())
SELECT DATEDIFF(YEAR, '1992.12.08', SYSDATETIME())




SELECT DATEPART(DW, SYSDATETIME())
SELECT DATEPART(MONTH, SYSDATETIME())
SELECT DATEPART(YEAR, SYSDATETIME())



SELECT DAY(SYSDATETIME())
SELECT MONTH(SYSDATETIME())
SELECT YEAR(SYSDATETIME())




-- Reqemlerle bagli ishler uchun

PRINT PI()
PRINT SIN(1.57)
PRINT POWER(2, 3)
PRINT RAND()
PRINT ABS(-2)
PRINT FLOOR(5.8)
PRINT CEILING(5.1)




-- Metinlere bagli ishler uchun


SELECT LEFT(Code, 2) FROM Books
SELECT RIGHT(Code, 2) FROM Books
SELECT UPPER(Publisher) FROM Books
SELECT LOWER(Publisher) FROM Books
SELECT SUBSTRING(Publisher, 2, 5) FROM Books
SELECT LEN(TRIM('    HAKUNA    '))
SELECT LTRIM('    HAKUNA    ')
SELECT RTRIM('    HAKUNA    ')



SELECT REVERSE(Publisher) FROM Books
SELECT REPLACE('Menim adim Turandir', 'Turandir', 'Turaldir')